---
- name: "install wireguard"
  ansible.builtin.package:
    name: "wireguard"
    state: "present"

- name: "install innernet"
  ansible.builtin.apt:
    deb: "https://github.com/tonarino/innernet/releases/download/v{{ innernet_version }}/innernet_{{ innernet_version }}_amd64.deb"

- name: "add server tasks if required"
  include_tasks: "server.yml"
  when: "'innernet_servers' in group_names"
