---
- name: "add grafana apt key"
  ansible.builtin.apt_key:
    url: https://packages.grafana.com/gpg.key

- name: "add grafana apt repo"
  ansible.builtin.apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
