---
name: ansible-2.12
dependencies:
  - python=3.9
  - pip
  - pip:
      - ansible==5.8.0
      - ansible-lint==6.2.2
      - pre-commit==2.19.0
      - pipdeptree==2.0.0
      - detect-secrets==1.2.0
      - netaddr==0.8.0
