---
name: ansible-2.10
dependencies:
  - python=3.9
  - pip
  - pip:
      - ansible==3.1.0
      - ansible-lint==5.0.2
      - pre-commit==2.10.1
      - pipdeptree==2.0.0
      - detect-secrets==1.1.0
      - netaddr==0.8.0
