---
- name: Master Playbook
  hosts: inthemainfra.me
  become: true
  roles:
    # yamllint disable rule:comments-indentation
    # - baseline
    # - bitwarden
    # - caddy
    # - container
    # - duo
    - factorio
    # - firewalld
    # - grafana
    # - innernet
    # - k3s
    # - ldap
    # - letsencrypt
    # - nvidia_container_runtime
    # - pihole
    # - plex
    # - proxmox
    # - step_ca
    # - swap
    # - vault
    # yamllint enable rule:comments-indentation
  handlers:
    - import_tasks: roles/caddy/handlers/main.yml
    - import_tasks: roles/firewalld/handlers/main.yml
