---
netmaker_version: "v0.14.2"
service: "netmaker"
netmaker_ui_container: "docker.io/gravitl/netmaker-ui:{{ netmaker_version }}"
netmaker_environments:
  - netmaker_server: "default"
    config:
      apihost: "api.{{ service }}.{{ domain }}"
      apiport: "8081"
      masterkey: "{{ lookup('password', '/dev/null length=15 chars=ascii_letters') }}"
      allowedorigin: "*"
      restbackend: true
      agentbackend: true
      dnsmode: "on"
