---
- name: setup caddy config
  ansible.builtin.blockinfile:
    path: "{{ caddy_config_location }}"
    marker: "# {mark} ANSIBLE MANAGED {{ service }}"
    block: "{{ caddyfile_block }}"
    create: true
    mode: 0644
    validate: caddy adapt --config %s --validate
  notify:
    - restart reverse proxy
