---
- name: get copr repo
  dnf:
    name: "dnf-command(copr)"
    state: present

- name: enable copr repo
  command:
    cmd: dnf copr -y enable @caddy/caddy
    warn: false

- name: install caddy
  dnf:
    name:
      - caddy
      - nss-tools
    state: latest

- name: Create caddyfile
  file:
    path: /etc/caddy/Caddyfile
    state: touch

- name: enable http/s in firewalld
  import_tasks: roles/firewalld/handlers/main.yml
  vars:
    firewalld_services:
      - http
      - https

- name: enable caddy service
  service:
    name: caddy
    state: started
    enabled: true
