---
- name: get copr repo
  dnf:
    name: "dnf-command(copr)"
    state: present

- name: check to see if repo exists
  stat:
    path: "/etc/yum.repos.d/_copr:copr.fedorainfracloud.org:group_caddy:caddy.repo"
  register: caddyrepo

# dnf copr -y enable @caddy/caddy
# that command results in a file with type=rpm-md, so dunno if it should be kept
# also has enabled_metadata: yes
- name: enable copr repo
  yum_repository:
    name: "copr:copr.fedorainfracloud.org:group_caddy:caddy"
    file: "_copr:copr.fedorainfracloud.org:group_caddy:caddy"
    baseurl: https://download.copr.fedorainfracloud.org/results/@caddy/caddy/epel-8-$basearch/
    description: "Copr repo for caddy owned by @caddy"
    skip_if_unavailable: yes
    gpgcheck: yes
    gpgkey: https://download.copr.fedorainfracloud.org/results/@caddy/caddy/pubkey.gpg
    repo_gpgcheck: no
    enabled: yes
  when: not caddyrepo.stat.exists

- name: fix copr repo
  ini_file:
    path: "/etc/yum.repos.d/_copr:copr.fedorainfracloud.org:group_caddy:caddy.repo"
    section: "copr:copr.fedorainfracloud.org:group_caddy:caddy"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  loop:
    - { option: type, value: rpm-md }
    - { option: enabled_metadata, value: 1 }
  when: not caddyrepo.stat.exists

- name: install caddy
  dnf:
    name:
      - caddy
      - nss-tools
    state: latest

- name: check to see if Caddyfile exists
  stat:
    path: /etc/caddy/Caddyfile
  register: caddyfile_exists

- name: create Caddyfile
  file:
    path: /etc/caddy/Caddyfile
    state: touch
  when: not caddyfile_exists.stat.exists

- name: enable http/s in firewalld
  import_tasks: roles/firewalld/handlers/main.yml
  vars:
    firewalld_services:
      - http
      - https

- name: enable caddy service
  service:
    name: caddy
    state: started
    enabled: true
