---
- name: disable caddy config
  ansible.builtin.blockinfile:
    path: "{{ caddy_config_location }}"
    marker: "# {mark} ANSIBLE MANAGED {{ service }}"
    state: absent
    validate: caddy adapt --config %s --validate
  notify:
    - restart reverse proxy
