---
- name: add caddy key
  ansible.builtin.apt_key:
    url: https://dl.cloudsmith.io/public/caddy/stable/cfg/gpg/gpg.155B6D79CA56EA34.key

- name: add caddy repository
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - deb https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main
    - deb-src https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main
