---
- name: add gpg key for repo
  ansible.builtin.apt_key:
    url: https://nvidia.github.io/nvidia-docker/gpgkey

- name: add repo
  ansible.builtin.get_url:
    url: "https://nvidia.github.io/nvidia-docker/ubuntu20.04/nvidia-docker.list"
    dest: /etc/apt/sources.list.d/nvidia-docker.list
    mode: "0644"

- name: install nvidia-container-toolkit (podman)
  ansible.builtin.apt:
    name: nvidia-container-toolkit
    state: latest
    update_cache: true # noqa: package-latest

- name: make hook directory if required
  ansible.builtin.file:
    path: /usr/share/containers/oci/hooks.d
    state: directory
    mode: "0755"

- name: copy hook
  ansible.builtin.copy:
    src: oci-nvidia-hook.json
    dest: /usr/share/containers/oci/hooks.d/oci-nvidia-hook.json
    mode: 0644

- name: uncomment no-cgroups in nvidia-container-runtime config
  ansible.builtin.replace:
    path: /etc/nvidia-container-runtime/config.toml
    regexp: "^#?no-cgroups = false"
    replace: "no-cgroups = true"

- name: test gpu passthrough works
  ansible.builtin.command: >-
    podman run --rm --security-opt=label=disable
      --hooks-dir=/usr/share/containers/oci/hooks.d/
      nvidia/cuda:11.0-base nvidia-smi
  register: nvidia_smi_output
  changed_when: false

- name: assert previous command has content
  ansible.builtin.assert:
    that: "'Driver Version' in nvidia_smi_output.stdout"
