---
- name: pull calibre-web container image
  containers.podman.podman_image:
    name: "{{ calibre_web_container }}"
    state: present

- name: ensure data directory exists
  file:
    path: /data/calibre-web/
    state: directory
    mode: 0700

- name: check to see if systemd service file exists already
  stat:
    path: /etc/systemd/system/container-calibre-web.service
  register: calibre_web_service

# localhost only so the reverse proxy can handle TLS termination for us
- name: start calibre-web
  containers.podman.podman_container:
    name: calibre-web
    image: "{{ calibre_web_container }}"
    state: present
    # network: slirp4netns
    publish:
      - 0.0.0.0:8083:8083
    volume:
      - /data/calibre-web/:/config/:Z
      - /data/books/:/books/:Z
    env:
      PUID: 0
      GUID: 0
      TZ: America/Los_Angeles
  register: calibre_web_command_result
  when: not calibre_web_service.stat.exists

- name: generate systemd service
  shell:
    cmd: >-
      podman generate systemd --name calibre-web >
      /etc/systemd/system/container-calibre-web.service
    creates: /etc/systemd/system/container-calibre-web.service
  when:
    - not calibre_web_service.stat.exists
    - calibre_web_command_result.changed

- name: stop calibre-web so systemd can take over
  containers.podman.podman_container:
    name: calibre-web
    image: "{{ calibre_web_container }}"
    state: stopped
  when:
    - not calibre_web_service.stat.exists
    - calibre_web_command_result.changed

- name: start systemd container-calibre-web service
  service:
    name: container-calibre-web
    state: started
    enabled: true
    daemon-reload: true

- name: add service to reverse proxy
  include_tasks:
    file: roles/caddy/tasks/add_service.yml
    apply:
      vars:
        caddyfile_block: |-
          calibre-web.{{ domain }} {
            reverse_proxy /* localhost:8083
          }
