---
auth_enabled: false

limits_config:
  ingestion_rate_mb: 24
  ingestion_burst_size_mb: 32

server:
  http_listen_address: 0.0.0.0
  http_listen_port: 3100

schema_config:
  configs:
    - store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  filesystem:
    directory: /loki/logs
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/boltdb-cache
    shared_store: filesystem

ingester:
  # 256 * 1024
  chunk_block_size: 262144
  max_transfer_retries: 0
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1

compactor:
  working_directory: /loki/compact
  shared_store: filesystem
  retention_enabled: true
  compaction_interval: 10m
  retention_delete_delay: 2h
