---
- name: include distro-specific pre-work
  include_tasks: "{{ ansible_distribution }}.yml"

- name: install docker/podman
  ansible.builtin.package:
    name: "{{ container_package }}"
    state: latest # noqa package-latest

- name: install Docker SDK for Python
  ansible.builtin.pip:
    name: docker
    state: latest # noqa package-latest
  when:
    - container_package == 'docker'
    - lookup('env', 'container') != 'docker'

- name: "stat /etc/containers/containers.conf"
  ansible.builtin.stat:
    path: "/etc/containers/containers.conf"
  register: "containers_conf"

# https://www.notion.so/yanghome/Home-Proxmox-a2bddaee846d4d75b146d43447202abe#ebc9398b4521421f94d6dbc73b8396c6
- name: fix kubic install
  block:
    - name: "fixup mount_program in storage.conf"
      ansible.builtin.replace:
        path: "/etc/containers/storage.conf"
        regexp: "^#(.*mount_program = .*)"
        replace: '\1'
    - name: "fixup containers.conf"
      ansible.builtin.copy:
        src: "containers.conf"
        dest: "/etc/containers/containers.conf"
        mode: "0644"
  when:
    - fixup_kubic_config is defined
    - fixup_kubic_config
    - containers_conf.stat.exists

- name: enable/start docker service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
  when:
    - container_package == 'docker'
    - lookup('env', 'container') != 'docker'

- name: "unbreak dbus.socket for podman"
  ansible.builtin.service:
    name: "dbus.socket"
    state: "started"
    enabled: "true"
  when:
    - container_package == 'podman'
    - lookup('env', 'container') != 'podman'
