---
- name: download k3s binary x64
  get_url:
    url: https://github.com/k3s-io/k3s/releases/download/{{ k3s_version }}/k3s
    checksum: sha256:https://github.com/k3s-io/k3s/releases/download/{{ k3s_version }}/sha256sum-amd64.txt
    dest: "{{ k3s_install_location }}/k3s" # checksum of this binary must match
    owner: root
    group: root
    mode: 0700 # why would you want ordinary users to run this

- name: copy k3s-killall.sh
  copy:
    src: k3s-killall.sh
    dest: "{{ k3s_install_location }}/k3s-killall.sh"
    owner: root
    group: root
    mode: 0700 # why would you want ordinary users to run this

- name: template k3s-uninstall
  template:
    src: k3s-uninstall.sh.j2
    dest: "{{ k3s_install_location }}/k3s-uninstall.sh"
    owner: root
    group: root
    mode: 0700 # why would you want ordinary users to run this

- name: setup symlinks
  file:
    src: "{{ k3s_install_location }}/k3s"
    dest: "{{ k3s_install_location }}/{{ item }}"
    state: link
    owner: root
    group: root
    mode: 0700 # why would you want ordinary users to run this
  loop:
    - crictl
    - ctr
    - kubectl

- name: install k3s service
  template:
    src: k3s.service.j2
    dest: "{{ k3s_systemd_config_location }}/k3s-{{ k3s_agent_type }}.service"
    owner: root
    group: root
    mode: 0644

- name: check for node-token
  stat:
    path: "{{ k3s_node_token_path }}"
    get_checksum: false
    get_attributes: false
    get_mime: false
  register: node_token_present

- name: run first time tasks
  import_tasks: master.yml
  when:
    - "'kube_master' in group_names"
    - node_token_present.stat.exists

- name: enable and start k3s server
  service:
    name: k3s-{{ k3s_agent_type }}
    enabled: true
    state: started
