---
- name: add hashicorp key (ubuntu)
  ansible.builtin.apt_key:
    url: https://apt.releases.hashicorp.com/gpg

# this step might take a while
- name: add vault repository (ubuntu)
  ansible.builtin.apt_repository:
    repo: deb https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main
    state: present
    update_cache: true
