---
k3s_version: v1.20.2+k3s1
k3s_install_location: /usr/local/bin
k3s_systemd_config_location: /etc/systemd/system
k3s_manifest_dir: /var/lib/rancher/k3s/server/manifests
k3s_node_token_path: /var/lib/rancher/k3s/server/node-token
k3s_agent_type: node
